# Generated by Django 5.2 on 2025-07-13 10:35

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('bout_order', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Fighter',
            fields=[
                ('fighter_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('draws', models.CharField(default='0', max_length=64)),
                ('height_in', models.IntegerField(blank=True, null=True)),
                ('weight_lb', models.IntegerField(blank=True, null=True)),
                ('reach_in', models.IntegerField(blank=True, null=True)),
                ('stance', models.CharField(blank=True, max_length=64, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bout',
            fields=[
                ('bout_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('result', models.CharField(blank=True, max_length=64, null=True)),
                ('method', models.CharField(blank=True, max_length=64, null=True)),
                ('ending_round', models.CharField(blank=True, max_length=64, null=True)),
                ('ending_time', models.CharField(blank=True, max_length=64, null=True)),
                ('time_format', models.CharField(blank=True, max_length=64, null=True)),
                ('referee', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_bouts', to='api.event')),
                ('fighter_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter_1_bouts', to='api.fighter')),
                ('fighter_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fighter_2_bouts', to='api.fighter')),
                ('winning_fighter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_bouts', to='api.fighter')),
            ],
        ),
    ]
