# Generated by Django 5.2 on 2025-08-12 23:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter',
            name='elo',
            field=models.FloatField(default=1500.0),
        ),
        migrations.AddField(
            model_name='fighter',
            name='elo_history',
            field=models.JSONField(default=api.models.Fighter.elo_history_default)
        ),
        migrations.AddField(
            model_name='fighter',
            name='peak_elo',
            field=models.FloatField(default=1500.0),
        ),
    ]
