/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as TestsTestsIdRouteImport } from './routes/tests/$testsId'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsTestsIdRoute = TestsTestsIdRouteImport.update({
  id: '/tests/$testsId',
  path: '/tests/$testsId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/tests/$testsId': typeof TestsTestsIdRoute
  '/events': typeof EventsIndexRoute
  '/tests': typeof TestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/tests/$testsId': typeof TestsTestsIdRoute
  '/events': typeof EventsIndexRoute
  '/tests': typeof TestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/tests/$testsId': typeof TestsTestsIdRoute
  '/events/': typeof EventsIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events/$eventId' | '/tests/$testsId' | '/events' | '/tests'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events/$eventId' | '/tests/$testsId' | '/events' | '/tests'
  id:
    | '__root__'
    | '/'
    | '/events/$eventId'
    | '/tests/$testsId'
    | '/events/'
    | '/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  TestsTestsIdRoute: typeof TestsTestsIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$testsId': {
      id: '/tests/$testsId'
      path: '/tests/$testsId'
      fullPath: '/tests/$testsId'
      preLoaderRoute: typeof TestsTestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  TestsTestsIdRoute: TestsTestsIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
